# ILPER 1.38 for Linux
#
# Copyright (c) 2008-2009  J-F Garnier
# Copyright (c) 2011-2012  Ch. Gottheimer
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# ----------------------------------------------------------------------------------
#
# Makefile    ILPER make(1)
#
# Specify USEASCII=yes to force the usage of ASCII border decoration
# Specify ILDEVICE=<device> to set a specific default device for the PILBox link
# Specify ILDISK=<LIF file> to set a specific default LIF image
#
# Take care of doing a make clean before changing the options above.
#
# 2011: ported on Linux by Ch. Gottheimer
# ---------------------------------------------------------------------------------


CC	= gcc
CFLAGS	= -g -Wall

LDFLAGS	= -g

LIBS	= -lncursesw -lpanel

VERSION	= version.c

ILPER = ilper

ILDISK := HDRIVE1.DAT

ILDEVICE := /dev/ttyUSB0

ifeq ($(USEASCII),yes)
CFLAGS  += -DUSEASCII
endif

TARGETS = $(ILPER)

SOURCES = ilmain.c ilper7.c ildisp.c ildrive.c ilvideo.c ilselfile.c \
	  $(VERSION)

MISC	= COPYING README NEWS DOCUMENTATION

OBJECTS	= $(SOURCES:%.c=%.o) 

TARDIR	:= ..

INSTALLDIR	:= $(HOME)/

ILPERMISC	= COPYING README ILPER.TXT DOCUMENTATION

BINDIR	:= bin/

MANDIR	:= man/man1/

INSTALL	= $(TARGETS)

.SUFFIXES:	.c .o #.xroms.so
.c.o:
	$(CC) -c $(CFLAGS) -DILDEVICE=\"$(ILDEVICE)\" -DILDISK=\"$(ILDISK)\" -o $@ $<

all:		.depend $(TARGETS)

$(ILPER):	$(OBJECTS) $(VERSION)
	$(CC) $(LDFLAGS) -o $@ $(OBJECTS) $(LIBS) $(LIBS_NCURSESW)

clean:
	@echo "Cleaning $(ILPER)"
	@\rm -f $(TARGETS) $(OBJECTS) *.o *.c~ *.h~ README~ COPYING~ VERSION~ Makefile~ scope.out display.out

clean-all:	clean
	@echo "Cleaning all $(ILPER)"
	@\rm -f .depend $(VERSION)

clean-tarball:	clean-all

clean-version:	clean-tarball
	@echo "Cleaning version $(ILPER)"
	@\rm -f VERSION PATCHLEVEL

$(VERSION):	VERSION PATCHLEVEL Makefile
	@( echo "$(ILPER) - Version "`cat VERSION` \#`cat PATCHLEVEL` )
	@( echo '// This is file is generated by Makefile - DO NOT EDIT' ; \
	   echo '// ===================================================' ; \
	   echo ; \
	   echo 'const char const $(ILPER)_vers[] = "'`cat VERSION`' #'`cat PATCHLEVEL`'";' ; \
	   echo 'const char const $(ILPER)_date[] = "('$(USER)@`hostname`') '`date `'";' ; \
	   echo 'const char const $(ILPER)_os[] = "'`uname -s -r`'";' ; \
	   echo ) > $@

VERSION:	 PATCHLEVEL
	@( echo $(PWD) | sed 's/^.*-//' ) > $@

PATCHLEVEL:
	@( test -e VERSION || touch VERSION )
	@( test "`basename $(PWD) | sed 's/^.*-//'`" != "`cat VERSION`" && rm -f VERSION )
	@( echo 0 ) > $@

install:	$(TARGETS)
	@echo "Installing $(ILPER) in $(INSTALLDIR)"
	@chmod 755 $(ILPER)
	@test -d $(INSTALLDIR)/$(BINDIR) || mkdir -p $(INSTALLDIR)/$(BINDIR)
	@cp -a $(ILPER) $(INSTALLDIR)/$(BINDIR)
	@test -d $(INSTALLDIR)/$(MANDIR) || mkdir -p $(INSTALLDIR)/$(MANDIR)
	@cp -a $(ILPER).1 $(INSTALLDIR)/$(MANDIR)

tarball:	VERSION
	@$(MAKE) clean-tarball
	@( TARBALL=`basename $(PWD)` ; \
           PATCHLVL=`cat PATCHLEVEL` ; \
	   echo "Building tarball $(TARDIR)/$${TARBALL}_$$PATCHLVL.tgz" ; \
           ( tar -C .. -zcf $(TARDIR)/$${TARBALL}_$$PATCHLVL.tgz $$TARBALL/ ; \
	     chmod 444 $(TARDIR)/$${TARBALL}_$$PATCHLVL.tgz ; \
	     \ls -l $(TARDIR)/$${TARBALL}_$$PATCHLVL.tgz ) ; \
	   echo $$((PATCHLVL + 1)) >PATCHLEVEL )

release:	VERSION
	echo "Closing version ilper `cat VERSION` #`cat PATCHLEVEL`"
	( echo "`cat VERSION` #`cat PATCHLEVEL`" ; echo "('$(USER)@`hostname`') '`date `" )>.tmp.TARBALL
	$(MAKE) tarball
	echo "Opening new version"
	( VERS=`cat VERSION | \
	    awk 'BEGIN{ FS="." }{ tn=$$3 ; if ($$tn == "") tn=0 ; printf("%u.%u.%u\n", $$1,$$2 + 1,0) }'`; \
	    echo $$VERS; \
	    cp -a $(PWD)/. ../ilper-$$VERS ; \
	    echo "RELEASE" >../ilper-$$VERS/PATCHLEVEL ; \
	    rm -f .tmp.TARBALL ; \
	    (cd ../ilper-$$VERS; \
               mv .tmp.TARBALL .TARBALL; \
               make clean-version ; \
               echo "RELEASE" >PATCHLEVEL; \
               $(MAKE) VERSION ) )

.depend:	Makefile $(VERSION) $(PATCHLEVEL)
	@touch $@
	@$(CC) -I. -MM $(CFLAGS) $(SOURCES) > $@

include .depend

