// This is file is generated by Makefile - DO NOT EDIT
// ===================================================

const char const ilper_vers[] = "1.40.0 #0";
const char const ilper_date[] = "(jmvansteene@Egeon) Tue Jul 7 21:49:03 CEST 2026";
const char const ilper_os[] = "Linux 6.6.114.1-microsoft-standard-WSL2";

