// This is file is generated by Makefile - DO NOT EDIT
// ===================================================

const char ilper_vers[] = "1.40.0 #RELEASE";
const char ilper_date[] = "(jmvansteene@Egeon) Thu Jul 23 21:21:35 CEST 2026";
const char ilper_os[] = "Linux 6.6.114.1-microsoft-standard-WSL2";

